### ISSUE TITLE
使用更现代化的依赖管理

### ISSUE THREAD

**Issue by qi7chen** [wuqunyong/APie#1]
C++的三方库依赖，可以使用[conan](https://conan.io/)或者[vcpkg](https://github.com/microsoft/vcpkg)

例如conan的配置：

conan.txt
```ini
[requires]
protobuf/3.15.5
libevent/2.1.12
lz4/1.9.3
yaml-cpp/0.6.3

[generators]
cmake

```

然后cmake里面增加一点东西

CMakeList.txt
```
conan_basic_setup()
target_link_libraries(md5 ${CONAN_LIBS})
```

然后运行环境，我觉得给一个[docker-compose.yml](https://docs.docker.com/compose/)把mysql,redis加起来，比给一个shell脚本更友好

如:

docker-compose.yml
```yaml
version: "3"

volumes:
    mysql-data:
    etcd-data:

services:
    etcd1:
        image: bitnami/etcd
        volumes:
            - etcd-data:/bitnami/etcd/data
        environment: 
            - ALLOW_NONE_AUTHENTICATION=yes
            - ETCD_NAME=etcd1
            - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
        ports:
            - 12379:2379
            - 12380:2380

    redis:
        image: redis:6-alpine
        ports:
            - 16379:6379
    
    mysqldb:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        volumes: 
            - ./etc/mysql:/etc/mysql/mysql.conf.d
            - mysql-data:/var/lib/mysql
        ports:
            - 13306:3306
        environment:
            MYSQL_ROOT_PASSWORD: LGrk4IaS0Wflxw
            MYSQL_DATABASE: gamedb
```
